import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import First from './components/template1'
import Input from './components/input'
const inter = Inter({ subsets: ['latin'] })
import MainPage from './components/app'

export default function Home() {
  return (
    <>
      <Head>
        <title>resume builder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
          {/* <h2>anil karikatti</h2> */}
          {/* <First/> */}
          {/* <Input/> */}

          <MainPage/>
      </main>
    </>
  )
}
